export const WORK_ORDER_KEYS = {
	LIST_WORK_ORDERS: "LIST_WORK_ORDERS",
	GET_WORK_ORDER: "GET_WORK_ORDER",
	CREATE_WORK_ORDER: "CREATE_WORK_ORDER",
	UPDATE_WORK_ORDER: "UPDATE_WORK_ORDER",
	CANCEL_WORK_ORDER: "CANCEL_WORK_ORDER",
};
